name: Win64

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

#env:
#  ACTIONS_RUNNER_DEBUG: true

jobs:
  raku:
    strategy:
      matrix:
        os:
#          - 'windows-latest'
#          - 'windows-2022'
          - 'windows-2019'
        raku-version:
#          - 'latest'
#          - '2024.06'
#          - '2024.03'
          - '2020.10'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Dependencies
        run: |
          choco install poppler
          zef install --/test --deps-only .
          raku -I. t/0-load-test.t
          raku -I. --ll-exception t/1-extract.t
      - name: Run Tests
        run: zef install .
